name: gocron-gorm-lock
services:
  postgres:
    image: postgres
    ports:
      - '5433:5432'
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo